### ISSUE TITLE
使用adguard+ss时，所有流量经过ss的都没法过滤，不知道什么情况

### ISSUE THREAD

**Issue by ltr970503** [qinyuhang/ShadowsocksX-NG#10]
![1](https://cloud.githubusercontent.com/assets/18322610/18008432/a1cf0272-6bda-11e6-9e82-51700e0deed5.jpg)
adguard已经选择过滤ss的流量，但是依然没有效果。。

**Comment by qinyuhang** [comment]
首先你用的好像不是我的这个app。我的这个叫ShadowsockaX-NG-R，而不是ShadowsocksX-R。
此外我没有adguard，暂时没法重现这个问题。因此可以给出一下log么？
最后给你一个可以尝试的方法，过滤不要选ShadowsocksX-NG或者ShadowsocksX-R，把过滤选项选为
~/Library/ShadowsocksX-NG/ss-local（假设你用的是我的这个branch，否则应该是ShadowsocksX-R）

ltr970503 <notifications@github.com>于2016年8月26日 周五22:17写道：

**Comment by ltr970503** [comment]
试了一下您的app，情况依旧，估计问题在于gui和ss-local是互相独立的？然后adguard并不支持把ss-local加入过滤清单。。

**Comment by qinyuhang** [comment]
gui和ss-local是独立的。因此要过滤需要过滤ss-local。adguard没用过，你可以去adguard的support问问如何过滤进程

ltr970503 <notifications@github.com>于2016年8月27日 周六08:09写道：

**Comment by ookangzheng** [comment]
可以用Adguard DNS官方的
176.103.130.130
176.103.130.131
放在你的Server DNS / Router
