### ISSUE TITLE
MACos

### ISSUE THREAD

**Issue by RainierBig** [qinyuhang/ShadowsocksX-NG#11]
10.22beta
安裝失敗

**Comment by RainierBig** [comment]
![89043dc76111fa28](https://cloud.githubusercontent.com/assets/9332645/18031638/48bd17c0-6d1d-11e6-9277-f4e8bdef6b82.jpg)

**Comment by Sharnodra** [comment]
我没这个问题，重新下载？

**Comment by qinyuhang** [comment]
需要在设置里面的安全选项选择信任所有开发者的app。

RainierBig <notifications@github.com>于2016年8月28日 周日12:45写道：

**Comment by qinyuhang** [comment]
<img width="681" alt="2016-08-28 12 49 43" src="https://cloud.githubusercontent.com/assets/6239057/18031653/eddf5aa6-6d1d-11e6-876c-a8e85ea6a378.png">
如果macOS10.12没有，请参考 http://www.th7.cn/system/mac/201606/170183.shtml
