### ISSUE TITLE
请教Shadowsocks python 和 ShadowsocksR

### ISSUE THREAD

**Issue by ookangzheng** [qinyuhang/ShadowsocksX-NG#12]
如同题目
这两个组要的差别在哪里？安全性还是速度更好，稳定？
Andoird / Ios 是否app也支持呀~~ 谢谢

**Comment by qinyuhang** [comment]
一样的，这个是GUI的，python的是命令行的而已。iOS找 [Potatso](https://potatso.com)   安卓找 [SSR](https://github.com/glzjin/shadowsocksr-android)
