### ISSUE TITLE
Build 失败。。。。。

### ISSUE THREAD

**Issue by oimken** [qinyuhang/ShadowsocksX-NG#17]
出错提示：

> d /Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-bfbtbuokimyopfbsnzixqyizhxjv/Build/Products/Debug/proxy_conf_helper normal x86_64
    cd /Volumes/Resources/Git/ShadowsocksX-NG
    export MACOSX_DEPLOYMENT_TARGET=10.10
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-bfbtbuokimyopfbsnzixqyizhxjv/Build/Products/Debug -L/Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-bfbtbuokimyopfbsnzixqyizhxjv/Build/Products/Debug/BRLOptionParser -F/Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-bfbtbuokimyopfbsnzixqyizhxjv/Build/Products/Debug -filelist /Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-bfbtbuokimyopfbsnzixqyizhxjv/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper.LinkFileList -mmacosx-version-min=10.10 -Xlinker -no_deduplicate -ObjC -lBRLOptionParser -fobjc-arc -fobjc-link-runtime -lPods-proxy_conf_helper -Xlinker -dependency_info -Xlinker /Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-bfbtbuokimyopfbsnzixqyizhxjv/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_dependency_info.dat -o /Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-bfbtbuokimyopfbsnzixqyizhxjv/Build/Products/Debug/proxy_conf_helper

ld: library not found for -lBRLOptionParser
clang: error: linker command failed with exit code 1 (use -v to see invocation)

请问怎么解决

**Comment by qinyuhang** [comment]
最后总结是说的 连接 BRLOptionParser 库失败，因此可以考虑是否是Pod库没装上？试试 pod install 安装一下？

oimken <notifications@github.com>于2016年9月9日 周五19:47写道：

**Comment by oimken** [comment]
已pod install的， 确认安装了 BRLOptionParser 库。太奇怪了，在
Build settings ->Search Paths->Library Search Paths 下
也添加了 
/Volumes/Resources/Git/ShadowsocksX-NG/Pods/BRLOptionParser/BRLOptionParser
这个直接的路径
但是就是一直报BRLOptionParser找不到

**Comment by qinyuhang** [comment]
pod.xcproj里面也有设置吗？proxy_conf_helper.h的搜索路径是否正确呢？如果还是不行，可否重新git clone一下呢？

oimken <notifications@github.com>于2016年9月9日 周五19:56写道：

**Comment by oimken** [comment]
重新下载了ZIP包，pod install, build 还是一样失败。。。。

> ld: warning: directory not found for option '-L/Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-euvwbnuyqogyfhgrfnfiyzwrgype/Build/Products/Debug/BRLOptionParser'
> ld: library not found for -lBRLOptionParser
> clang: error: linker command failed with exit code 1 (use -v to see invocation)


XCODE 版本 7.3.1

**Comment by qinyuhang** [comment]
如果不使用zip呢？用命令行git clone可否成功build？

oimken <notifications@github.com>于2016年9月9日 周五20:20写道：

**Comment by oimken** [comment]
刚GIT了， 一样的错误
```
ld: warning: directory not found for option '-L/Users/Ken/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-bfbtbuokimyopfbsnzixqyizhxjv/Build/Products/Debug/BRLOptionParser'
ld: library not found for **-lBRLOptionParser**
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**-lBRLOptionParser** 是不是有问题？

**Comment by qinyuhang** [comment]
我的在自己的电脑上build没有问题，travis-ci的测试build
https://travis-ci.org/qinyuhang/ShadowsocksX-NG 也没有问题，如果只有你失败的话，还是需要从 1.
项目clone；2. 工具环境 中找问题了。

oimken <notifications@github.com>于2016年9月9日 周五20:37写道：

**Comment by oimken** [comment]
谢谢您的耐心回复，我找找原因。

**Comment by qinyuhang** [comment]
还是建议你检查一下工具环境 :p

oimken <notifications@github.com>于2016年9月9日 周五20:44写道：

**Comment by oimken** [comment]
已找到原因。已成功BUIILD。谢谢您的帮助。

**Comment by qinyuhang** [comment]
可否分享一下具体问题以及排查情况呢？方便其他的人如果需要参考？

oimken <notifications@github.com>于2016年9月10日 周六00:09写道：

**Comment by oimken** [comment]
是我自己太蠢。。用了xcodeproj 来 build....都不好意思说。。。
