### ISSUE TITLE
退出客戶端後不能正確保存狀態

### ISSUE THREAD

**Issue by itzhaclea** [qinyuhang/ShadowsocksX-NG#20]
無論上一次退出前客戶端的狀態是打開或否，每次啟動軟件後都是關閉，需要手動打開。

不知道這是一個 bug 還是 feature。

**Comment by Sharnodra** [comment]
我觉得，无论关闭时的状态是打开与否，在每次启动软件后，都自动打开更为合适，毕竟用户启动软件的目的，就是打开Shadowsocks服务了，省一步操作。
如果觉得直接自动打开不太友好，可以推出一个通知消息作为补偿。：）

**Comment by qinyuhang** [comment]
这是一个feature 否则 ss-local
会一直在后台运行，等于没有退出程序。如果想要保存状态但是又要退出ss-local，这个属于新feature

Sharnodra <notifications@github.com>于2016年9月11日 周日02:57写道：

**Comment by itzhaclea** [comment]
還是希望能在啟動軟件後自動打開 SS，每次開機後需要點一下開關來開啟有些繁瑣。

**Comment by qinyuhang** [comment]
可以考虑加到高级设置里面。我回去试试加上

Itzhac <notifications@github.com>于2016年9月11日 周日15:33写道：

**Comment by qinyuhang** [comment]
已有 打开时自动连接 选项，在主菜单。Release build 在最新的release里面可下载
