### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by ltr970503** [qinyuhang/ShadowsocksX-NG#21]
1：建议服务器测速能有一个进度什么的
2：服务器列表中，如果有备注的节点只显示备注，不显示ip和端口号
3：整合“代理”里的高级设置和总的高级设置，不然很杂
4：建议换成少女粉的图标2333

**Comment by qinyuhang** [comment]
第一点，merge的上游的，我正在和他讨论异步并发的测速，现在的测速有一些bug，将会在后来的修复；
第二点，在主菜单中只会显示备注（如果没有备注只会显示IP），服务器列表中，因为有必须要分开类似复用的IP或域名，因此使用了 备注＋IP＋端口 来区分，如果有必要的话，可以弄到高级设置里面设置为自定义只显示某一个（比如备注，或者IP）；
第三点是具体指？
第四点，米有得到破娃的钦定哇。。换了感觉23333333
