### ISSUE TITLE
关于服务器记录的删除

### ISSUE THREAD

**Issue by Sharnodra** [qinyuhang/ShadowsocksX-NG#22]
希望能让服务器记录支持多选以批量删除。
顺便一提，关于删除，有点小问题，删除一个服务器记录后，会跳到并选择最下面的一条服务器记录。
然后删到剩最后一个的时候，会无法删除，能否删到空？
另外，如果正在连接的服务器被删除了，菜单里的已连接服务器名称不会更新，展开后发现删剩下的那一项被勾选。
加油！

**Comment by qinyuhang** [comment]
已修复
