### ISSUE TITLE
10.12使用了r6版本无论全局还是pac均无法上网

### ISSUE THREAD

**Issue by xDidi3r** [qinyuhang/ShadowsocksX-NG#23]
使用全局的时候直接显示“safari不能连接到服务器”，所有网站都打不开。
使用PAC的时候打开youtube之类的会一直卡着无法载入，没被墙的网都能正式上。
服务器测速都是十几ms的延时。

**Comment by qinyuhang** [comment]
可能是服务器出问题了，已知服务器节点问题会导致这个情况，是因为流量发送到节点，无法从节点转发出去，可否检查一下节点？

xdidi3r <notifications@github.com>于2016年9月16日 周五21:25写道：

**Comment by xDidi3r** [comment]
节点没有问题，我使用原来的shadowsocksX可以正常上网

**Comment by Sharnodra** [comment]
10.12，R6 ，试了开全局，暂未发现此问题。

**Comment by qinyuhang** [comment]
或者服务端是纯SS有可能出现这个问题

xdidi3r <notifications@github.com>于2016年9月16日 周五21:36写道：

**Comment by afayge** [comment]
看一下~ /Library/'Application Support'/ShadowsocksX-NG/ss-local-2.4.8 下面的的ss-local 有么有执行的权限，如果没有添加执行权限。

#!/bin/sh

#  install_ss_local.sh
#  ShadowsocksX-NG
#
#  Created by 邱宇舟 on 16/6/6.
#  Copyright © 2016年 qiuyuzhou. All rights reserved.


cd `dirname "${BASH_SOURCE[0]}"`
mkdir -p "$HOME/Library/Application Support/ShadowsocksX-NG/ss-local-2.4.8"
cp -f ss-local "$HOME/Library/Application Support/ShadowsocksX-NG/ss-local-2.4.8/"
rm -f "$HOME/Library/Application Support/ShadowsocksX-NG/ss-local"
ln -s "$HOME/Library/Application Support/ShadowsocksX-NG/ss-local-2.4.8/ss-local" "$HOME/Library/Application Support/ShadowsocksX-NG/ss-local"

cp -f libcrypto.1.0.0.dylib "$HOME/Library/Application Support/ShadowsocksX-NG/"

echo done

**Comment by qinyuhang** [comment]
是否是同样的问题呢？ https://github.com/qinyuhang/ShadowsocksX-NG/issues/24 最新的commit已经解决，可以尝试 `chmod +x "$HOME/Library/Application Support/ShadowsocksX-NG/ss-local-2.4.8/ss-local" "`

**Comment by xDidi3r** [comment]
啊，在忙工作没注意回复大家，我晚上回去试试！

**Comment by xDidi3r** [comment]
尝试了最新的release，已经解决了这个问题！非常感谢大家~
