### ISSUE TITLE
10.12  无法使用

### ISSUE THREAD

**Issue by afayge** [qinyuhang/ShadowsocksX-NG#24]
2个shadowsocks服务都没有办法使用，确认服务器是好的，openwrt 可以上网，服务器是shadowsocks-libv版本。

**Comment by qinyuhang** [comment]
可否检查一下是不是这个原因？如果是，将会在以后release修正 https://github.com/shadowsocks/ShadowsocksX-NG/issues/55#issuecomment-247816611

**Comment by afayge** [comment]
自己已经修复了。~/Library/'Application Support'/ShadowsocksX-NG/ss-local-2.4.8 吓得 ss-local 没有执行权限，加了执行权限，就可以了。
