### ISSUE TITLE
请问一下如何在“显示日志…”中查看最近请求数据

### ISSUE THREAD

**Issue by clockcloud** [qinyuhang/ShadowsocksX-NG#30]
原先使用的 ssx 中可以在系统日志中搜索 shadowsocks 查看哪些地址走了代理，然而现在似乎并找不到。。

**Comment by qinyuhang** [comment]
你说的是原版的SahdowsocksX吗？这两个实现原理不一样

ReveEver <notifications@github.com>于2016年9月23日 周五09:32写道：

**Comment by clockcloud** [comment]
恩 之前使用的是原版
能否在未来版本中实现该功能？

**Comment by qinyuhang** [comment]
由于和原版原理不一样，需要看看原理上可否实现

ReveEver <notifications@github.com>于2016年9月24日 周六10:45写道：

**Comment by qinyuhang** [comment]
在 高级设置中启用啰嗦模式，然后所有请求的IP方向和域名会在` ~/Library/Logs/ss-local.log`  中查询到
