### ISSUE TITLE
修改当前active的节点地址 或直接删除该节点 主菜单中节点地址不会自动改变

### ISSUE THREAD

**Issue by Dwwwwww** [qinyuhang/ShadowsocksX-NG#35]
[初始状态](http://i1.piimg.com/4851/bcf6b566f4767a44.jpg) 
[修改节点地址](http://i1.piimg.com/4851/48eb3a39e989a8f9.jpg) 
[删除节点](http://i1.piimg.com/4851/99cc9b681c648484.jpg)

**Comment by qinyuhang** [comment]
https://github.com/qinyuhang/ShadowsocksX-NG/commit/d26410aae649482e0d696687613ef5b3298e64c6
