### ISSUE TITLE
OTA与verify_sha1留一个就好了啊_(:з」∠)_

### ISSUE THREAD

**Issue by Dwwwwww** [qinyuhang/ShadowsocksX-NG#36]
根据https://github.com/breakwa11/shadowsocks-rss/blob/master/ssr.md
verify_sha1就是OTA😂

**Comment by qinyuhang** [comment]
这个OTA是留给原版用户的啦

Dwwwwww <notifications@github.com>于2016年10月7日 周五09:35写道：
