### ISSUE TITLE
更改mac窗口配色后，SS-NG任务栏小图标不会自动更新配色

### ISSUE THREAD

**Issue by porea** [qinyuhang/ShadowsocksX-NG#39]
Before:
![screen shot 2016-10-09 at 5 01 34 pm](https://cloud.githubusercontent.com/assets/12146151/19218316/1303ea14-8e42-11e6-8cad-b4d278f22cc8.png)

After:
![screen shot 2016-10-09 at 5 01 38 pm](https://cloud.githubusercontent.com/assets/12146151/19218317/134a0cf6-8e42-11e6-9b48-0bd1ed948700.png)

**Comment by porea** [comment]
mac 10.12 / SS-NG-R7

**Comment by qinyuhang** [comment]
solved https://github.com/qinyuhang/ShadowsocksX-NG/releases/tag/1.3.4-R8
