### ISSUE TITLE
服务器列表里加个Duplicate功能吧

### ISSUE THREAD

**Issue by Sharnodra** [qinyuhang/ShadowsocksX-NG#4]
<img width="116" alt="2016-08-22 5 06 16" src="https://cloud.githubusercontent.com/assets/8577653/17849281/b0814c24-688a-11e6-9fc3-0db8869b4d28.png">

方便服务器信息的添加√

**Comment by qinyuhang** [comment]
这个可以，下个版本加一下。

Sharnodra <notifications@github.com>于2016年8月22日 周一17:08写道：

**Comment by qinyuhang** [comment]
已增加，现在放在右边似乎有点丑，但是放在左边找不到简洁的符号来表示复制，你可有任何好一点的设计呢？ @Sharnodra 
Release 下载地址 https://github.com/qinyuhang/ShadowsocksX-NG/releases

**Comment by Sharnodra** [comment]
我印象中，普遍做法是，在 + 和 - 的中间插入一项，图标是由两个白色矩形上下叠层的，跟 ❐ 有点像。
@qinyuhang

**Comment by qinyuhang** [comment]
好的 我回去查一下unicode有没有这个符号。

Sharnodra <notifications@github.com>于2016年8月22日 周一22:00写道：

**Comment by qinyuhang** [comment]
更新了图标，可以去release里面下载了

**Comment by Sharnodra** [comment]
感谢！不过我觉得，将“复制”的字号缩小一些（主要是让其上下的内边距增大，和加减号的内边距差不多），可能会更和谐一些。
<img width="258" alt="2016-08-23 11 21 00" src="https://cloud.githubusercontent.com/assets/8577653/17879349/e0171466-6923-11e6-9113-05b681d281d8.png">

**Comment by qinyuhang** [comment]
这个是为了考虑像素点的问题，再缩一个像素会导致和屏幕像素点不切合，图形变模糊的。暂时先用这个吧。如果有更好的图像再更新
Sharnodra <notifications@github.com>于2016年8月23日 周二11:25写道：

**Comment by Sharnodra** [comment]
涨知识了。
话说更新好勤快。
╮(╯▽╰)╭

**Comment by qinyuhang** [comment]
😀

Sharnodra <notifications@github.com>于2016年8月23日 周二18:27写道：
