### ISSUE TITLE
一点小建议。。。

### ISSUE THREAD

**Issue by JinRulin** [qinyuhang/ShadowsocksX-NG#40]
<img width="174" alt="2016-10-09 16 09 56" src="https://cloud.githubusercontent.com/assets/20963140/19219022/1cfb8812-8e3b-11e6-8941-67159e69d1e5.png">

这个名字长的都不能完整显示了。。。强迫症看了好难受！
改成ShadowsocksX-NG或者ShadowsocksX-N等等什么的、简洁一点，如何？
还有现在的显示网速功能能用了吗？（我没试）PS:如果不能用的话，就给取消吧、万一点上了恢复好麻烦

**Comment by qinyuhang** [comment]
这个名字你可以自己改的。。。。
关于网速显示，现在就是这个按钮不再触发功能了，请放心使用。
