### ISSUE TITLE
macOS Sierra 下无法使用

### ISSUE THREAD

**Issue by NonexistentAkarin** [qinyuhang/ShadowsocksX-NG#41]
系统是macOS 10.12，无论是最新的r8版还是release版，即使是打开全局模式，都无法使用。

本来怀疑是ss-local没有给权限的问题，查看后发现/Library/Application\ Support/ShadowsocksX-NG/下根本没有ss-local相关的文件或文件夹，而只有一个proxy_conf_helper。

尝试执行install_helper，install_privoxy，install_ss_local这3个脚本文件，提示done后/Library/Application\ Support/ShadowsocksX-NG/依然只有proxy_conf_helper。

非常奇怪的问题，本来国庆的时候还是好用的，之后不知怎么就再也不能翻墙了……

**Comment by qinyuhang** [comment]
请注意。。ss-local 不在 `/Library/Application\ Support/ShadowsocksX-NG/` 而在 `~/Library/Application\ Support/ShadowsocksX-NG/` (绝对路径是`$HOME/Library/Application\ Support/ShadowsocksX-NG/`) 请检查这个文件夹下是否有 ss-local 的情况。
或者，在高级设置里面打开 啰嗦模式，再从系统console.app 中 `~/Library/Logs` 里面 找到 ss-local 的日志上传（比如有peers invalid argument之类的）

**Comment by NonexistentAkarin** [comment]
谢谢。。~/Library/Application\ `Support/ShadowsocksX-NG/下是有ss-local那些文件的，尝试提权但是依旧不能用。开启啰嗦模式后，尝试开启全局访问几个网站，ss-local.log为空，privoxy.log不断提示
> 2016-10-10 14:34:16.800 7fffeae73 Info: Privoxy version 3.0.26
2016-10-10 14:34:16.801 7fffeae73 Info: Program name: /Users/akari/Library/Application Support/ShadowsocksX-NG/privoxy
2016-10-10 14:34:16.801 7fffeae73 Fatal error: can't check configuration file '/Users/akari/Library/Application Support/ShadowsocksX-NG/privoxy.config':  No such file or directory

但是该目录下确实是有这个文件的，怀疑是不是还是权限问题。。。

**Comment by qinyuhang** [comment]
这里说的是 privoxy的配置文件问题，可以尝试一下 1）关掉 菜单里面的 http 带路 2）替换掉 privoxy的配置文件

Akaza Akari <notifications@github.com>于2016年10月10日 周一14:43写道：

**Comment by NonexistentAkarin** [comment]
已经关闭HTTP代理了，依然无法FQ，提示

> 未连接到互联网
代理服务器出现问题，或者地址有误。

扫了一下系统被占用的端口，发现设置的Socks5监听端口没有被占用。。。
然后ss-local.log也一直是空
ss服务器地址和帐号没问题，Android上可以用

**Comment by qinyuhang** [comment]
OK 所以有可能是 ss-local 没有被启动？可以尝试一下 仅运行ss-local嘛

**Comment by NonexistentAkarin** [comment]
OK了已经弄好了，刚才执行了一下start-ss-local.sh提示

> /Users/akari/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist: Service is disabled

发现原来是Shadowsocks的启动代理不知道怎么被关闭了，重新开启即可使用
非常感谢！

**Comment by zhfish** [comment]
#44  
http代理有个小问题，有个pcre依赖，重新编译了下
