### ISSUE TITLE
r8 fix 全局模式下 chrome 无法打开任何网页

### ISSUE THREAD

**Issue by SurDuet** [qinyuhang/ShadowsocksX-NG#42]
系统是10.11.6, r8 fix版, 打开全局模式后 Safari 正常, chrome 所有网页均无法打开

显示为

There is no Internet connection

**Comment by qinyuhang** [comment]
可以临时关闭掉 全局模式的 http 代理设置。

**Comment by SurDuet** [comment]
it works thanks

**Comment by zhfish** [comment]
#44

**Comment by zhfish** [comment]
or 
`brew install pcre`
