### ISSUE TITLE
mac sierra安装后Boot Camp不能正常下载windows支持软件。

### ISSUE THREAD

**Issue by expandcode** [qinyuhang/ShadowsocksX-NG#43]
不太能确定是不是由于该软件导致的。

**Comment by qinyuhang** [comment]
Boot Camp is not related with shadowsocks... maybe you can describe this problem in detail?

**Comment by expandcode** [comment]
@qinyuhang 你好，谢谢回复。昨天Boot Camp一直网络错误。试过公司网络，家里网络，手机热点，每个网络试过全局代理（socks，http）。都不行。今天实在受不了，直接格式化重新安装了，没有安装shadowsocks-ng，打开boot camp一切正常。不懂网络知识，mac的log写了'http load failed'.问Apple的客服boot camp相关的网络知识，对方也不懂。希望大神普及下知识。

#我提个小意见，版本更新太快了！！！！还是稳定再放出来比较好。
我一直在https://github.com/qinyuhang/ShadowsocksX-NG/releases这里下载。这里是最新版的么？

#另想了解下为什么没有osx 10.12后缀的版本。。

提点小意见，希望不要见怪。做了点微小的贡献，蛤蛤

**Comment by qinyuhang** [comment]
1. 你是指 macOS 系统可以正常使用，但是Boot Camp的网络不能使用？
2. Boot Camp的网络在什么情况下不能使用呢？是打开了SS（SS处于什么状态 PAC 全局 手动？）
3. 这个本身就是开源项目，更新快就是开源项目的特点，如果有发现问题欢迎发issue，如果可以贡献代码欢迎发PR，发issue、贡献代码都会成为开源项目前进的力量！
4. macOS10.11withSwift3 指的是系统最低要求10.11，另有10.10指的是最低要求10.10（10.10使用的是swift2.3的版本，接下来的更新会稍晚于swift3版本）

**Comment by expandcode** [comment]
@qinyuhang 
1.macOS可以正常使用，Boot Camp会报网络错误
2.有9种情况，网络情况---1.家中，2.公司,3.联通iphone热点       代理情况--1.Pac，2.全局，3.无代理
1对1全部不行。
3.开源的好。可惜我能力不够，目前努力进步。以后也能像你一样贡献代码。创造有价值的东西。
4.谢谢，完全明白。

--------------------
疑问：
1..下载下来是Shadowsocks-NG-R8,我自己修改应用名为Shadowsocks-NG。这样影响正常使用么？

**Comment by qinyuhang** [comment]
我一直用虚拟机的，所以Boot Camp的情况不太了解。
下载下来的程序可以随意改名，不会对使用造成任何影响。
