### ISSUE TITLE
请问服务器的配置信息可不可以备份或者有没有文件保存在什么路径下？

### ISSUE THREAD

**Issue by 171621** [qinyuhang/ShadowsocksX-NG#47]
Win版有gui-config.json文件可以保存配置信息方便备份。请问这个macOS的版本有没有类似存贮配置信息的文件或者可以备份配置信息的功能？

**Comment by qinyuhang** [comment]
可以直接使用win版的gui-config.json文件导入。只需要保存一份win版的gui-config.json即可。
