### ISSUE TITLE
服务器批量ping的功能

### ISSUE THREAD

**Issue by Sharnodra** [qinyuhang/ShadowsocksX-NG#5]
是否易于实现？

**Comment by qinyuhang** [comment]
这个貌似有人在上游提出过，但是这个我不太敢动手，涉及到服务器的response，有可能会被fail2ban。需要一些参考资料，或者等上游更新

Sharnodra <notifications@github.com>于2016年8月23日 周二18:30写道：

**Comment by Sharnodra** [comment]
OK，话说，whitelist.pac里的socks5端口还是1080，要不要变成1086？

**Comment by qinyuhang** [comment]
这个是自动生成的，点击主菜单的更新whitelist会下载回本地～/.ShadowsocksX-NG ，此目录里面的pac文件是正确的就行

Sharnodra <notifications@github.com>于2016年8月23日 周二18:51写道：

**Comment by Sharnodra** [comment]
更新后本地上看到的就是1080，好像没啥影响？

**Comment by qinyuhang** [comment]
发现了 是socks5: 127.0.0.1:1080 这个可能是处理问题。我检查一下代码。

Sharnodra <notifications@github.com>于2016年8月23日 周二18:58写道：

**Comment by qinyuhang** [comment]
已修正代码，暂时还没build，我先去看看10.12 pac问题 可能一块merge了再build一个

Sharnodra <notifications@github.com>于2016年8月23日 周二18:58写道：

**Comment by qinyuhang** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/issues/20#issuecomment-244550163

**Comment by qinyuhang** [comment]
已增加，在最新的develop分支
