### ISSUE TITLE
代理设置为“IP白名单”时 PAC 失效

### ISSUE THREAD

**Issue by aenerv7** [qinyuhang/ShadowsocksX-NG#51]
版本 1.3.4-R8-build3 中发现的问题，当代理设置为 “IP白名单” 时，PAC 设置是失效的，我从 “系统偏好设置” 里的 “网络” 中，将 “自动代理配置” 栏中填写的 “ http://127.0.0.1:8090/whiteiplist.pac” 地址拷贝出来使用浏览器访问，结果被拒绝，其他代理模式下则没有这个问题。

**Comment by qinyuhang** [comment]
已确认。
是否只有IP白名单发生问题？
经过我复现，现在是 域名白名单 是OK的，但是IP白名单有问题。

**Comment by aenerv7** [comment]
目前只发现 “IP白名单” 的代理模式出现了这个问题，“域名白名单” 的代理模式是正常的

**Comment by qinyuhang** [comment]
已确认。
晚上我会检查一下是哪里的问题。

**Comment by aenerv7** [comment]
看到有更新了我这边刚刚试了一下，刚更新的 1.3.4-R8-build4 版本应该是已经解决了这个问题，我的 iMac 上已经正常了

**Comment by qinyuhang** [comment]
问题已解决，请下载 1.3.4-R8-build4
