### ISSUE TITLE
这个软件对服务商有限制嘛？

### ISSUE THREAD

**Issue by cooliean** [qinyuhang/ShadowsocksX-NG#52]
https://www.shadowsocks.biz/member/
我冲这里的买的服务就是不可以，
用原来的软件Shadowsocks 2.6.3可以，为什么啊。
我是mac  10.12 
很郁闷啊，以为想修改点东西。
不知道有没有遇到我这样问题的

**Comment by qinyuhang** [comment]
没有任何限制。

**Comment by cooliean** [comment]
@qinyuhang 
那我这个 https://www.shadowsocks.biz/member/  地方的用不了，我怎么排除问题呢，可以指点一下不呢，我用下面的这个2.6.3 是可以用的，我现在是两个一起打开，你的软件打开了（我在你的源码上面加了一下打开的时候的一些设置。），他的也打开了就可以用，或者只打开他的也可以用。
https://github.com/shadowsocks/shadowsocks-iOS/releases

**Comment by qinyuhang** [comment]
额
我觉得你应该找错了。。
这个事情应该让服务商给你解决，因为我这边是不会接触你的具体配置信息的。
PPS：不知道你在软件本身做了什么修改，这个就更增加了问题定位的难度了。
如果可以，附上log等，可以参考一下。
log在 ~/Library/Logs/ss-local.log

**Comment by cooliean** [comment]
好的，谢谢了

**Comment by qinyuhang** [comment]
对系统设置的修改不会影响软件的正常使用。请自查具体设置，比如有没有在扫码的时候使用了老版本的二维码导致配置错位（不支持老版本的二维码）https://github.com/qinyuhang/ShadowsocksX-NG/issues/7

**Comment by qinyuhang** [comment]
我觉得你应该找错人了。。。。
这个事情应该交给软件服务商来搞定。因为对于开发者来说，绝对不会接触的就是你的数据，你的配置。所以我们不会去碰你的数据的，但是不碰你的数据，就没法确定问题，因此这个问题我没法解决。
PS 不知你在源码上加了什么修改？这个就更加不知道问题所在了。
最后，本软件是给SSR开的版本，但是兼容原版SS，如果有发生参数填写错误的情况请自查哦。
