### ISSUE TITLE
扫描二维码功能不可用

### ISSUE THREAD

**Issue by fax001** [qinyuhang/ShadowsocksX-NG#54]
最新的1.3.4版本 macOS 10.11
扫描二维码不可用 导入功能点击也没有反应

**Comment by qinyuhang** [comment]
最新版本是 1.3.5-R8-build1，请试试这个

**Comment by fax001** [comment]
@qinyuhang 1.3.5 还是不可用 对二维码的内容有明确规则限制吗？

**Comment by fax001** [comment]
应该是二维码识别算法的问题 二维码识别不够敏感

**Comment by MilooHub** [comment]
我这边也是安装 1.3.5 R8(1) 版本后（macOS 10.12），发现无法识别二维码。
