### ISSUE TITLE
升级Sierra后ss不可用 重新安装配置成功后缺少库文件

### ISSUE THREAD

**Issue by micweiyi** [qinyuhang/ShadowsocksX-NG#55]
Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local
  Referenced from: /Users/michelle/Library/Application Support/ShadowsocksX-NG/ss-local

**Comment by zhfish** [comment]
没经历升级，我重装的，没问题， 你删掉一下目录应该就好了
`rm -rf /Users/michelle/Library/Application\ Support/ShadowsocksX-NG`

**Comment by BROBIRD** [comment]
@zhfish 确实不能用

**Comment by zhfish** [comment]
sierra的SIP又对用户目录加限制了？ 
我一直关掉SIP的，一切正常

**Comment by qinyuhang** [comment]
很奇怪，我开着SIP，homebrew 装过 pcre 但是是没问题的。要不要我们考虑一下吧pcre打包进app bundle。

**Comment by qinyuhang** [comment]
https://github.com/qinyuhang/ShadowsocksX-NG/issues/58 PCRE问题已经修复
