### ISSUE TITLE
Sierra下不可用

### ISSUE THREAD

**Issue by a39908646** [qinyuhang/ShadowsocksX-NG#58]
Process:               ss-local [6478]
Path:                  /Applications/ShadowsocksX-NG-R8.app/Contents/Resources/ss-local
Identifier:            ss-local
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [6472]
Responsible:           ss-local [6478]
User ID:               501

Date/Time:             2016-10-27 17:21:51.527 +0800
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        41985B1A-1117-7B7D-3E24-A6AF8C140BE2

Sleep/Wake UUID:       C5186486-97F5-4850-A5D5-35605F48C991

Time Awake Since Boot: 28000 seconds
Time Since Wake:       1800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Applications/ShadowsocksX-NG-R8.app/Contents/Resources/ss-local
  Reason: image not found

Binary Images:
       0x107df1000 -        0x107e31fe3 +ss-local (0) <2CB86239-5C60-3673-959D-C6214AA7A8A8> /Applications/ShadowsocksX-NG-R8.app/Contents/Resources/ss-local
       0x10c2e2000 -        0x10c31f287  dyld (421.2) <13A9466A-2576-3ABB-AD9D-D6BC16439B8F> /usr/lib/dyld
    0x7fffd0fac000 -     0x7fffd1090ff3  libcrypto.0.9.8.dylib (64) <4CB423CE-0B86-334A-9335-FEE75198024F> /usr/lib/libcrypto.0.9.8.dylib

**Comment by qinyuhang** [comment]
pcre问题已经修复
