### ISSUE TITLE
OSX 10.12.1无法使用

### ISSUE THREAD

**Issue by ouyangmland** [qinyuhang/ShadowsocksX-NG#64]
默认	13:13:02.896985 +0800	wirelessproxd	Started to advertise for type 12 with error (null)
默认	13:13:02.897207 +0800	wirelessproxd	Started to advertise for type 16 with error (null)
默认	13:13:02.897675 +0800	identityservicesd	calling continuityDidStartAdvertisingOfType:Activity
默认	13:13:02.901117 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
默认	13:13:02.901578 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
默认	13:13:02.902124 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
默认	13:13:02.903941 +0800	taskgated	MacOS error: -67062
默认	13:13:02.898955 +0800	kernel	AMFI: allowing exception handler for 'ss-local' (1118) because the process is unsigned.
默认	13:13:02.905133 +0800	ReportCrash	os_activity_diagnostic_for_pid() failed!
默认	13:13:02.905227 +0800	ReportCrash	Failed while requesting activity/breadcrumb diagnostics
默认	13:13:02.916987 +0800	ReportCrash	Saved crash report for <private> to <private>
默认	13:13:02.918036 +0800	ReportCrash	Removing excessive log: file:///Users/hiohoi/Library/Logs/DiagnosticReports/ss-local_2016-10-31-130942_HioHoideMacBook-Air.crash
默认	13:13:04.179069 +0800	pkd	No plugins found to match query <private>
默认	13:13:04.879882 +0800	wirelessproxd	Advert timer expired for client 12 after 2.00 seconds
默认	13:13:04.880580 +0800	identityservicesd	Continuity update advertising with data: Advertising request of type 12, priority 6, UseFG 290 (181.25 ms), data <083b1210 2b838d99 95167609 7003>, connectable 1
默认	13:13:04.880887 +0800	wirelessproxd	Updating advert request for client 12 after 2.00 seconds
默认	13:13:04.880989 +0800	wirelessproxd	Start advertising for process identityservicesd (275) of type 12 with advertising interval 290 (181.25 ms)
默认	13:13:04.881244 +0800	wirelessproxd	advertisingRulesOSX - advertisements: (
        {
        kCBAdvAppleMfgTypeKey = 12;
        kCBAdvDataAppleMfgData = <13ff4c00 0c0e083b 12102b83 8d999516 76097003>;
        kCBAdvOptionUseFGInterval = 0;
    },
        {
        kCBAdvAppleMfgTypeKey = 16;
        kCBAdvDataAppleMfgData = <07ff4c00 10020b00>;
        kCBAdvOptionUseFGInterval = 0;
    }
)
默认	13:13:04.881498 +0800	wirelessproxd	Requesting to start advertising for clients 12 16  with (
        {
        kCBAdditionalAppleMfgAdvertisements =         (
                        {
                kCBAdvAppleMfgTypeKey = 16;
                kCBAdvDataAppleMfgData = <07ff4c00 10020b00>;
                kCBAdvOptionUseFGInterval = 0;
            }
        );
        kCBAdvDataAppleMfgData = <13ff4c00 0c0e083b 12102b83 8d999516 76097003>;
        kCBAdvOptionUseFGInterval = 0;
        kCBScanOptionIsPrivilegedDaemon = 1;
    }
)
默认	13:13:04.907176 +0800	wirelessproxd	Started to advertise for type 12 with error (null)
默认	13:13:04.907392 +0800	wirelessproxd	Started to advertise for type 16 with error (null)
默认	13:13:04.907776 +0800	identityservicesd	calling continuityDidStartAdvertisingOfType:Activity
默认	13:13:05.347095 +0800	kernel	IO80211Interface::updateReport _peerManager is missing

默认	13:13:06.403873 +0800	CommCenter	#watchdog #I Callback Watchdog: checkin 437
默认	13:13:06.404153 +0800	CommCenter	#watchdog #I Server Watchdog: checkin 437
错误	13:13:09.425944 +0800	cloudd	NSURLSessionTask finished with error - code: -1001
默认	13:13:09.426338 +0800	cloudd	TIC TCP Conn Cancel [60:0x7f8745e99a40]
默认	13:13:09.426378 +0800	cloudd	[Request 0x7f8745e979a0] URLSession:task:didCompleteWithError:
默认	13:13:09.426459 +0800	cloudd	[Request 0x7f8745e979a0] Request completed with error
错误	13:13:09.426706 +0800	cloudd	Finishing request with error 0x7f8745e81790
错误	13:13:09.426882 +0800	cloudd	HTTP load failed (error code: 89 [1:89])
错误	13:13:09.427106 +0800	cloudd	Error fetching configuration from the server: <private>
默认	13:13:09.427262 +0800	cloudd	[Operation 0x7f8745c5f7a0] Operation is finishing on callback queue with an error
默认	13:13:09.429170 +0800	cloudd	[Operation 0x7f8745c5f7a0] Operation is getting flow controlled due to a local error
默认	13:13:09.429461 +0800	cloudd	[Operation 0x7f8745e98cb0] Couldn't get server configuration
默认	13:13:09.429952 +0800	cloudd	[Operation 0x7f8745e98cb0] Operation is finishing on callback queue with an error
默认	13:13:09.430055 +0800	cloudd	[Operation 0x7f8745e98cb0] Operation is getting flow controlled due to a local error
默认	13:13:09.431029 +0800	Safari	Failed to save record: <CKError 0x608000a5a1f0: "Network Failure" (4/-1001); "请求超时。">
默认	13:13:12.913664 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
默认	13:13:12.914377 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
默认	13:13:12.915096 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
默认	13:13:12.916937 +0800	taskgated	MacOS error: -67062
默认	13:13:12.911898 +0800	kernel	AMFI: allowing exception handler for 'ss-local' (1119) because the process is unsigned.
默认	13:13:12.918460 +0800	ReportCrash	os_activity_diagnostic_for_pid() failed!
默认	13:13:12.918575 +0800	ReportCrash	Failed while requesting activity/breadcrumb diagnostics
默认	13:13:12.930104 +0800	ReportCrash	Saved crash report for <private> to <private>
默认	13:13:12.931171 +0800	ReportCrash	Removing excessive log: file:///Users/hiohoi/Library/Logs/DiagnosticReports/ss-local_2016-10-31-130952_HioHoideMacBook-Air.crash
默认	13:13:15.273460 +0800	pkd	No plugins found to match query <private>
默认	13:13:21.403907 +0800	CommCenter	#watchdog #I Callback Watchdog: checkin 438
默认	13:13:21.404076 +0800	CommCenter	#watchdog #I Server Watchdog: checkin 438
默认	13:13:22.335663 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
默认	13:13:22.336057 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
默认	13:13:22.336637 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
默认	13:13:22.349512 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
默认	13:13:22.371212 +0800	open	subsystem: com.apple.securityd, category: unixio, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
默认	13:13:22.380369 +0800	open	subsystem: com.apple.libsqlite3, category: logging, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
默认	13:13:22.475216 +0800	QQ	[0x7fb291b29000] Created session
默认	13:13:22.490423 +0800	QQ	[0x7fb291b29000] Decoding: C0 0x00280028 0x0000304A 0x22111100 0x00000000 872
默认	13:13:22.490464 +0800	QQ	[0x7fb291b29000] Options: 1x-1 [FFFFFFFF,FFFFFFFF] 00054060
默认	13:13:22.490576 +0800	QQ	[0x7fb291b29000] Decoding completed without errors
默认	13:13:22.491356 +0800	QQ	[0x7fb2928c0000] Releasing session
默认	13:13:22.766742 +0800	gamed	GKClientProxy: clientForBundleID:
默认	13:13:22.767055 +0800	gamed	GKClientProxy: updateIfRecentlyInstalled
默认	13:13:22.772197 +0800	gamed	GKClientProxy: clientForBundleID:
默认	13:13:22.773450 +0800	gamed	GKClientProxy: updateIfRecentlyInstalled
默认	13:13:22.834619 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
默认	13:13:22.927108 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
默认	13:13:22.927570 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
默认	13:13:22.928233 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
默认	13:13:22.929946 +0800	taskgated	MacOS error: -67062
默认	13:13:22.924299 +0800	kernel	AMFI: allowing exception handler for 'ss-local' (1122) because the process is unsigned.
默认	13:13:22.931026 +0800	ReportCrash	os_activity_diagnostic_for_pid() failed!
默认	13:13:22.931105 +0800	ReportCrash	Failed while requesting activity/breadcrumb diagnostics
默认	13:13:22.939981 +0800	ReportCrash	Saved crash report for <private> to <private>
默认	13:13:22.941056 +0800	ReportCrash	Removing excessive log: file:///Users/hiohoi/Library/Logs/DiagnosticReports/ss-local_2016-10-31-131002_HioHoideMacBook-Air.crash

**Comment by ouyangmland** [comment]
上面是SS的日志

**Comment by qinyuhang** [comment]
log中说 crash都放在 file:///Users/hiohoi/Library/Logs/DiagnosticReports/ss-local_2016-10-31-130952_HioHoideMacBook-Air.crash 了 ，可否附件到里面呢？

**Comment by ouyangmland** [comment]
@qinyuhang 可以

**Comment by ouyangmland** [comment]
http://share.weiyun.com/5d2e2ad056bb0dbcbc1386d516a62260

**Comment by ouyangmland** [comment]
@qinyuhang http://share.weiyun.com/5d2e2ad056bb0dbcbc1386d516a62260

**Comment by ouyangmland** [comment]
@qinyuhang 能下载ss-local_2016-10-31-130952_HioHoideMacBook-Air.crash这个吗？上面的链接

**Comment by qinyuhang** [comment]
参考 https://github.com/qinyuhang/ShadowsocksX-NG/issues/60 的解决方法。安装pcre
这个问题将会在未来几个版本得到修复。

**Comment by ouyangmland** [comment]
@qinyuhang 好的谢谢

**Comment by yangleitj** [comment]
我遇到同样问题，10.12确实brew install pcre可以解决。

**Comment by qinyuhang** [comment]
PCRE 问题已经在最新版修复，10.11 _get_clock() 问题正在追因
