### ISSUE TITLE
無法通過掃碼添加 SSR 服務器

### ISSUE THREAD

**Issue by itzhaclea** [qinyuhang/ShadowsocksX-NG#7]
ShadowsocksX-R 可以做到這一點：
> https://github.com/yichengchen/ShadowsocksX-R

測試了下，原版的 S-NG 和 這個支持 SSR 的S-NG 都沒有辦法通過掃描 QR Code 添加 SSR 服務器，添加 SS 服務器則可以正常工作。

**Comment by qinyuhang** [comment]
目前只支持新版的qr码，也就是扫码以后是 ssr:// 的ssr二维码。

Itzhac <notifications@github.com>于2016年8月23日 周二23:54写道：

**Comment by qinyuhang** [comment]
@itzhaclea 请试试这个二维码
![test ssr qr](https://cloud.githubusercontent.com/assets/6239057/17899691/c0031452-698e-11e6-9a1f-19d35f8f2fed.png)

**Comment by itzhaclea** [comment]
感謝解答，這個 issue 可以關閉了。

**Comment by qinyuhang** [comment]
目前由于之前有兼容老版本的SSR配置二维码（ **_ss://_** => [SS, SSR] ）存在（这个其实是无奈之举，大家更乐意用分开的 **_ss://_** => ss 、 **_ssr://_** => SSR）
但是本版本没有做兼容老版本的二维码（只支持 **_ss://_** => ss 和 **_ssr://_** => ssr  ，因为目前来看是趋势）
后期比较空闲的时候会考虑重构和增加兼容老版本二维码（即 **_ss://_** = > [SS, SSR]）的功能（但是会引入SSR配置转QR双重选择的困境）。
目前仅支持新版本的SSR二维码。如果有疑问，请使用回复中的SSR二维码检测

![ssr test qr](https://cloud.githubusercontent.com/assets/6239057/17900344/8739f1e2-6991-11e6-9f50-0c6c5a36d967.png)

**Comment by itzhaclea** [comment]
在掃描服務商提供的 SSR 的 QR Code 時，大概有 60% 的機率會失敗，這是重複實驗了30次後得到的結論。先前由於只是試了幾次，結果均為失敗後就提了這個 issue. 但是掃瞄您提供的 QR Code, 則沒有這個問題出現。是因為服務商提供的是老版本的 QR Code?

**Comment by qinyuhang** [comment]
有可能是二维码不清晰吧？我测试的时候都是用尺寸比较大的二维码测试的。可能尺寸小了会失败？或者有的的老的版本会失败？你可以用手机扫码软件扫一下
看看二维码开头是ss://（老版本）还是ssr://（新版本）

Itzhac <notifications@github.com>于2016年8月24日 周三00:42写道：

**Comment by itzhaclea** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/21023855/17901107/90696aec-6994-11e6-8866-76f80fe8d46e.jpg)
是 SSR 的開頭。至於二維碼大小，您提供的是 574*574, 服務商提供的是 542*544. 通過截圖計算，可能有出入。

**Comment by qinyuhang** [comment]
额 那我倒是很好奇了。
当然我说的尺寸是指占据电脑屏幕的比例，大点好识别……
另外
目前能想到最后一种可能是二维码编码不规范，在base64解码的时候出问题了。要确定这个还需要更多信息才好。
可惜没法取到app log（log里面可能有敏感信息，勿要随意公开，如果有心，请处理一下给我，马赛克掉密码 port等）。
或者等等看有没有更多人反馈同一个问题。（请问问你的朋友们有碰见这个问题吗？）
感谢反馈。

Itzhac <notifications@github.com>于2016年8月24日 周三00:51写道：

**Comment by itzhaclea** [comment]
請問 app log 的提取方式是在 console 裡以 networking 為關鍵字進行搜索嗎？

**Comment by qinyuhang** [comment]
在console里面搜索 Shadowsocks 就好

**Comment by itzhaclea** [comment]
<img width="927" alt="bildschirmfoto" src="https://cloud.githubusercontent.com/assets/21023855/17919157/d958d9ea-69fd-11e6-9917-920dae8734d1.png">
在進行多次的掃碼後的日誌，感覺沒有有效信息。
