### ISSUE TITLE
复制后的profile被关联上，改一个全部都会被更改

### ISSUE THREAD

**Issue by qinyuhang** [qinyuhang/ShadowsocksX-NG#8]
复制后的profile被关联上，改一个全部都会被更改

**Comment by qinyuhang** [comment]
已修正 最新下载地址 https://github.com/qinyuhang/ShadowsocksX-NG/releases/

**Comment by Sharnodra** [comment]
新问题，复制出来的profile虽然不一样了，但是连接任意一个，所复制出来的不同服务器也会被勾选。
<img width="88" alt="2016-08-27 9 52 59" src="https://cloud.githubusercontent.com/assets/8577653/18027845/becd3684-6ca0-11e6-84ee-136aadae50b6.png">

**Comment by qinyuhang** [comment]
这样吗？很好奇你复制完了之后有改过里面的设置吗？

Sharnodra <notifications@github.com>于2016年8月27日 周六21:54写道：

**Comment by Sharnodra** [comment]
是的，我复制后，仅修改了服务器地址和备注。

**Comment by qinyuhang** [comment]
嗯，发现这个问题了，我明天检查一下是哪里的问题。

**Comment by Sharnodra** [comment]
3q

**Comment by qinyuhang** [comment]
问题解决 https://github.com/qinyuhang/ShadowsocksX-NG/releases/tag/1.3.3-R5
