### ISSUE TITLE
谁来说说gpg验证是什么鬼?

### ISSUE THREAD

**Issue by ShaoXinSen** [qinyuhang/ShadowsocksX-NG#84]
gpg: Signature made Sat Dec 24 10:27:07 2016 CST using RSA key ID 73EB5E11
gpg: Can't check signature: No public key

需要一个公钥?

然后是这样吗?:

gpg --keyserver pgp.mit.edu --recv-keys 73EB5E11
gpg: requesting key 73EB5E11 from hkp server pgp.mit.edu
gpgkeys: key 73EB5E11 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: Not found
gpg: keyserver communications error: Bad public key
gpg: keyserver receive failed: Bad public key

不懂该怎么进行作者说的gpg检查

**Comment by haxpor** [comment]
Happen to me the same. I'd love to check gpg.

**Comment by qinyuhang** [comment]
PUBLIC KEY https://github.com/qinyuhang/Pubkey

**Comment by ShaoXinSen** [comment]
@qinyuhang  OK
