### ISSUE TITLE
增加一键配置服务器的功能。

### ISSUE THREAD

**Issue by Sunbelife** [qinyuhang/ShadowsocksX-NG#9]
手动配置列表实在麻烦，希望能增加一个配置文件，可以手动批量添加，会方便许多。

**Comment by qinyuhang** [comment]
目前没有统一格式的配置文件，可以考虑支持surge格式的配置文件。

**Comment by qinyuhang** [comment]
release https://github.com/qinyuhang/ShadowsocksX-NG/releases/tag/1.3.3-R5
